In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [11]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [15]:
import pandas as pd
import numpy as np

In [26]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [27]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [28]:
df['Target'] = dataset.target

In [29]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [32]:
df_copy = df[df['Target'] != 2]

In [33]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    Target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [34]:
## independent and dependent feature

In [40]:
X = df_copy.iloc[:,:-1]

In [41]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [42]:
y = df_copy.iloc[:,-1]

In [43]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: Target, Length: 100, dtype: int32

In [44]:
## trainn test split 
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42,test_size=0.30)

In [56]:
## model training 
from sklearn.linear_model import LogisticRegression

In [57]:
classifier =LogisticRegression()

In [58]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [72]:
classifier.predict_proba(X_test)

array([[0.00138809, 0.99861191],
       [0.01727551, 0.98272449],
       [0.00347239, 0.99652761],
       [0.96617439, 0.03382561],
       [0.93735729, 0.06264271],
       [0.9683378 , 0.0316622 ],
       [0.99250204, 0.00749796],
       [0.03399256, 0.96600744],
       [0.97156709, 0.02843291],
       [0.97628569, 0.02371431],
       [0.95059671, 0.04940329],
       [0.95665604, 0.04334396],
       [0.00488183, 0.99511817],
       [0.98387903, 0.01612097],
       [0.01029701, 0.98970299],
       [0.97905311, 0.02094689],
       [0.00240222, 0.99759778],
       [0.00146722, 0.99853278],
       [0.97162994, 0.02837006],
       [0.95705813, 0.04294187],
       [0.00818164, 0.99181836],
       [0.02348375, 0.97651625],
       [0.95558061, 0.04441939],
       [0.98204816, 0.01795184],
       [0.02859986, 0.97140014],
       [0.97787188, 0.02212812],
       [0.97990865, 0.02009135],
       [0.01679268, 0.98320732],
       [0.96627907, 0.03372093],
       [0.00173338, 0.99826662]])

In [59]:
y_test_pred = classifier.predict(X_test)

In [60]:
y_test_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1])

In [68]:
## confussion matrix, accuricy scorem classification report

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


In [69]:
print(confusion_matrix(y_test_pred, y_test ))

[[17  0]
 [ 0 13]]


In [70]:
print(accuracy_score(y_test_pred, y_test ))

1.0


In [71]:
print(classification_report(y_test_pred, y_test ))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [74]:
## HyperParameter tuning

In [76]:
## GridSearchCv
from sklearn. model_selection import GridSearchCV

In [84]:
parameters = {
    'penalty': ('l1', 'l2', 'elasticnet',None),
    'C': [1,10]
}

In [85]:
gsc_clf = GridSearchCV(classifier, param_grid=parameters, cv=5)

In [86]:
gsc_clf.fit(X_train,y_train)

c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
20 fits failed out o

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [87]:
gsc_clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [94]:
classifier2 = LogisticRegression(C=1, penalty='l2')

In [95]:
classifier2.fit(X_train, y_train)

LogisticRegression(C=1)

In [96]:
y_test_pres_hyper = classifier2.predict(X_test)

In [97]:
y_test_pres_hyper

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1])

In [98]:
## randamized search cv

In [100]:
from sklearn.model_selection import RandomizedSearchCV

In [102]:
random_clf = RandomizedSearchCV(LogisticRegression(), param_distributions=parameters, cv=5)

In [105]:
random_clf.fit(X_train, y_train)

c:\Users\USER\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:318: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1186: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
c:\Users\USER\anaconda3\Lib\site-packages\sklearn\linear_model\_

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [106]:
random_clf.best_params_

{'penalty': 'l2', 'C': 1}